export const UPDATE_TRANSACTION_ID = 'UPDATE_TRANSACTION_ID';
export const UPDATE_TRANSACTION_CURRENCIES = 'UPDATE_TRANSACTION_CURRENCIES';
export const UPDATE_TRANSACTION_DETAILS = 'UPDATE_TRANSACTION_DETAILS';
export const UPDATE_TRANSACTION_AMOUNT = 'UPDATE_TRANSACTION_AMOUNT';
